export const pacientes = [
  {
    id: 1,
    name: "John",
    lastname: "Doe",
    email: "johndoe@example.com",
    phone: 1234567890,
    pet: "Max",
    kind: "Dog",
    breed: "Labrador",
  },
  {
    id: 2,
    name: "Jane",
    lastname: "Smith",
    email: "janesmith@example.com",
    phone: 9876543210,
    pet: "Bella",
    kind: "Cat",
    breed: "Persian",
  },
  {
    id: 3,
    name: "Michael",
    lastname: "Johnson",
    email: "michaeljohnson@example.com",
    phone: 4567891230,
    pet: "Charlie",
    kind: "Dog",
    breed: "Golden Retriever",
  },
  {
    id: 4,
    name: "Emily",
    lastname: "Brown",
    email: "emilybrown@example.com",
    phone: 7891234560,
    pet: "Luna",
    kind: "Cat",
    breed: "Siamese",
  },
  {
    id: 5,
    name: "David",
    lastname: "Miller",
    email: "davidmiller@example.com",
    phone: 3216549870,
    pet: "Rocky",
    kind: "Dog",
    breed: "German Shepherd",
  },
];

export const turnos = [
  {
    vet: "Dr. Jack",
    pet: "Rocky",
    date: "2021-01-01",
    hour: "10:00 AM",
    details: "appointment details 1",
    id: 1,
  },
  {
    vet: "Dr. Lisa",
    pet: "Jack",
    date: "2021-01-02",
    hour: "11:00 AM",
    details: "appointment details 2",
    id: 2,
  },
  {
    vet: "Dr. Jack",
    pet: "Luna",
    date: "2021-01-03",
    hour: "12:00 PM",
    details: "appointment details 3",
    id: 3,
  },
  {
    vet: "Dr. Lisa",
    pet: "Charlie",
    date: "2021-01-04",
    hour: "13:00 PM",
    details: "appointment details 4",
    id: 4,
  },
  {
    vet: "Dr. Jack",
    pet: "Joe",
    date: "2021-01-05",
    hour: "14:00 PM",
    details: "appointment details 5",
    id: 5,
  },
];
