export const pacientes = [
  {
    id: 1,
    nombre: "John",
    apellido: "Doe",
    email: "johndoe@example.com",
    telefono: 1234567890,
    mascota: "Max",
    especie: "Dog",
    raza: "Labrador",
  },
  {
    id: 2,
    nombre: "Jane",
    apellido: "Smith",
    email: "janesmith@example.com",
    telefono: 9876543210,
    mascota: "Bella",
    especie: "Cat",
    raza: "Persian",
  },
  {
    id: 3,
    nombre: "Michael",
    apellido: "Johnson",
    email: "michaeljohnson@example.com",
    telefono: 4567891230,
    mascota: "Charlie",
    especie: "Dog",
    raza: "Golden Retriever",
  },
  {
    id: 4,
    nombre: "Emily",
    apellido: "Brown",
    email: "emilybrown@example.com",
    telefono: 7891234560,
    mascota: "Luna",
    especie: "Cat",
    raza: "Siamese",
  },
  {
    id: 5,
    nombre: "David",
    apellido: "Miller",
    email: "davidmiller@example.com",
    telefono: 3216549870,
    mascota: "Rocky",
    especie: "Dog",
    raza: "German Shepherd",
  },
];
