export const pacientes = [
  {
    id: 1,
    name: "John",
    lastname: "Doe",
    email: "johndoe@example.com",
    phone: 1234567890,
    pet: "Max",
    kind: "Dog",
    breed: "Labrador",
  },
  {
    id: 2,
    name: "Jane",
    lastname: "Smith",
    email: "janesmith@example.com",
    phone: 9876543210,
    pet: "Bella",
    kind: "Cat",
    breed: "Persian",
  },
  {
    id: 3,
    name: "Michael",
    lastname: "Johnson",
    email: "michaeljohnson@example.com",
    phone: 4567891230,
    pet: "Charlie",
    kind: "Dog",
    breed: "Golden Retriever",
  },
  {
    id: 4,
    name: "Emily",
    lastname: "Brown",
    email: "emilybrown@example.com",
    phone: 7891234560,
    pet: "Luna",
    kind: "Cat",
    breed: "Siamese",
  },
  {
    id: 5,
    name: "David",
    lastname: "Miller",
    email: "davidmiller@example.com",
    phone: 3216549870,
    pet: "Rocky",
    kind: "Dog",
    breed: "German Shepherd",
  },
];
